name: Need checks
description: Verify or wait for commit status check

branding:
  icon: check-circle
  color: green

inputs:
  token:
    description: GitHub token with proper permissions to query the API
    default: ${{ github.token }}
  repository:
    description: GitHub repository to wait for
    default: ${{ github.repository }}
  ref:
    description: git ref to check status on
    default: ${{ github.ref }}
  workflow:
    description: Restrict checks to a given workflow
  wait:
    description: Wait for all status check
    default: false
  wait_interval:
    description: time interval (in seconds) between checks while waiting
    default: 60
  wait_timeout:
    description: max time to wait if defined
  conclusions:
    description: comma separated list of accepted conclusions
    default: success,skipped


runs:
  using: docker
  image: docker://ghcr.io/noirbizarre/need-checks:main
